### ISSUE TITLE
Problem importing mpv on macOS

### ISSUE THREAD

**Issue by MaT1g3R** [MaT1g3R/ene#6]
```
Traceback (most recent call last):
  File "/Users/umi/Projects/Python/ene/ene/player.py", line 18, in <module>
    import mpv
  File "/Users/umi/.pyenv/versions/ene/lib/python3.6/site-packages/mpv.py", line 42, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

**Comment by MaT1g3R** [comment]
Need to use `brew install mpv` instead of `brew cask install mpv`
